US10 fuse search
gwittm/Digital-Recipe-Book pull request #40
Opened 2023-11-20 09:31 UTC by gwittm

2023-11-20 10:57 UTC, NikRoe requested changes
Hi there,

great work and search bar 👏 

I noticed that you fetch your recipes twice and left you a comment to make this part of your code more efficient.

Please take a look at it :)

Best regards 👋

2023-11-20 10:57 UTC, NikRoe commented on components/Search/FuseSearchRecipe.js
> +  // fieldNormWeight: 1,
I would remove all commented out code

2023-11-20 10:57 UTC, NikRoe commented on components/Search/FuseSearchRecipe.js
> +          Copyright 2023 Fonticons, Inc. --{" "}
I would remove this

2023-11-20 10:57 UTC, NikRoe commented on components/Search/FuseSearchRecipe.js
you are fetching your api route (`/api/recipes`) twice.

Once in your useEffect and once using useSWR.
This is not very efficient.

You should decide on having either only the useEffect and fetch or the useSWR fetch.

When only working with useEffect and fetch, you could create your own isLoading state that is true when the fetch begins and gets set to false once the fetch has been completed.

When working with useSWR you can pass an options object as a parameter. This object can have a key `onSuccess` that contains a callback function as its value. This is where you have access to the fetched data and set the fuse. 
It looks similar to this:

```js
const { data: recipes, isLoading, error } = useSWR(`/api/recipes`, {
    onSuccess: (fetchedRecipes) => {
      setFuse(new Fuse(fetchedRecipes, fuseOptions));
    },
  });
```

Please decide on either using useSWR or the useEffect with fetch and change your code according to your decision.

2023-11-20 10:57 UTC, NikRoe commented on components/Search/FuseSearchRecipe.js
> +  });
chained ternary operators are really hard to read. How about this:

```suggestion
const alphabeticallySortedRecipes = recipes.toSorted((a, b) => {
  if (a.title < b.title) {
    return -1;
  }
  if (a.title > b.title) {
    return 1;
  }
  return 0;
});
```

and `.toSorted()` is a new array method that does the same as `.sort()` while not mutating the original array.

2023-11-21 09:43 UTC, NikRoe requested changes
Hi there,

well done! I like that you chose the useEffect approach over the simple copying of the useSWR approach I suggested 👏 

I think your useEffect can be improved by resetting the error state and I left a suggestion that also gets rid of some repetition.

Ergo: You are almost there, only one teeny tiny change left 🙌

2023-11-21 09:43 UTC, NikRoe commented on components/Search/FuseSearchRecipe.js
> +  }, []);
If an error occurs, you currently don't reset it anywhere.

I would recommend changing your code to this:

```suggestion
useEffect(() => {
  async function getRecipes() {
    // Reset the error state at the beginning of each call
    setError(null);
    setIsLoading(true);

    try {
      const response = await fetch(`/api/recipes`);
      const fetchedRecipes = await response.json();

      setRecipes(fetchedRecipes);
      setFuse(new Fuse(fetchedRecipes, fuseOptions));
    } catch (fetchError) {
      setError(fetchError);
    } finally {
      // Always turn off loading indicator, regardless of the outcome
      setIsLoading(false);
    }
  }

  getRecipes();
}, []);
```

2023-11-21 10:03 UTC, gwittm commented
Thank you for your suggestions :)

2023-11-21 10:19 UTC, NikRoe approved these changes
Nicely done

2023-11-21 11:24 UTC, merged